# Generated by Django 4.1.3 on 2022-12-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='date_edited',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='study_level',
            field=models.CharField(choices=[('first', '1'), ('second', '2'), ('third', '3')], default='1', max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
