# Generated by Django 4.1.3 on 2022-12-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image_url',
            field=models.URLField(max_length=5000, null=True),
        ),
    ]
