# Generated by Django 4.1.3 on 2022-12-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_student_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image_url',
            field=models.CharField(max_length=8000, null=True),
        ),
    ]
