# Generated by Django 4.1.3 on 2022-12-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_course_course_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='private_code',
            field=models.IntegerField(max_length=6, null=True),
        ),
    ]
