# Generated by Django 4.1.3 on 2022-12-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_student_private_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='private_code',
            field=models.IntegerField(max_length=6, null=True, unique=True),
        ),
    ]
