# Generated by Django 4.1.3 on 2022-12-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_alter_student_private_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='private_code',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
