# Generated by Django 4.1.3 on 2022-12-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_alter_student_private_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image_file',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(choices=[('IT', 'information Technology'), ('Azure', 'Azure'), ('AWS', 'AWS'), ('AI', 'Artificial Intelligence')], default=None, max_length=30),
        ),
    ]
