# Generated by Django 4.1.3 on 2022-12-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='messages',
            name='date_edited',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
