# Generated by Django 4.1.3 on 2022-12-06 16:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0017_rename_messages_usermessages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserMessages',
            new_name='UserMessage',
        ),
    ]
