# Generated by Django 4.1.3 on 2022-12-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_rename_usermessages_usermessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(choices=[('IT', 'information Technology'), ('Azure', 'Azure'), ('AWS', 'AWS'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Ethical hacking', 'Ethical hacking')], default=None, max_length=30),
        ),
    ]
