# Generated by Django 4.1.3 on 2022-12-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(default=None, max_length=300)),
                ('condition', models.CharField(choices=[('Good', 'Good'), ('Better', 'Better'), ('Best,', 'Best')], default=None, max_length=300)),
                ('price', models.FloatField()),
                ('summary', models.TextField()),
            ],
        ),
    ]
