# Generated by Django 4.1.3 on 2022-12-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_date_added_item_date_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_url',
            field=models.CharField(max_length=8000, null=True),
        ),
    ]
